STICKERS_DIR = Stickers
STICKERS_OBJS_DIR = .objs/$(STICKERS_DIR)

STICKERS_OBJS = Image StickerSheet
STICKERS_DIR_OBJS = $(patsubst %, $(STICKERS_DIR)/%.o, $(STICKERS_OBJS))
OBJS += $(STICKERS_DIR_OBJS)
