SPANNINGTREE_DIR=SpanningTree
SPANNINGTREE_OBJS_DIR=.objs/$(SPANNINGTREE_DIR)

SPANNINGTREE_OBJS=SpanningTree
SPANNINGTREE_DIR_OBJS=$(patsubst %, $(SPANNINGTREE_DIR)/%.o, $(SPANNINGTREE_OBJS))
OBJS += $(SPANNINGTREE_DIR_OBJS)